services:
  weather-api-nginx:
    image: nginx:alpine
    container_name: weather-api-nginx
    ports:
      - "8080:80"
    volumes:
      - ../public:/var/www/html/public
      - ../src:/var/www/html/src
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - weather-api-php
    networks:
      - weather-network

  weather-api-php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    container_name: weather-api-php
    volumes:
      - ../:/var/www/html
    networks:
      - weather-network

  weather-api-redis:
    image: redis:alpine
    container_name: weather-api-redis
    ports:
      - "6379:6379"
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge