version: '3.8'

services:
  weather-api-nginx:
    image: nginx:alpine
    container_name: weather-api-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - type: bind
        source: C:\Users\Guilherme 3s\Desktop\Projetos de Programação\weather-api\public
        target: /var/www/html/public
    depends_on:
      - weather-api-php
    networks:
      - weather-network

  weather-api-php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    container_name: weather-api-php
    volumes:
      - type: bind
        source: C:\Users\Guilherme 3s\Desktop\Projetos de Programação\weather-api
        target: /var/www/html
    networks:
      - weather-network
    environment:
      - PHP_FPM_USER=www-data
      - PHP_FPM_GROUP=www-data
      - WEATHER_API_URL=${WEATHER_API_URL}
      - WEATHER_API_KEY=${WEATHER_API_KEY}

  weather-api-redis:
    image: redis:alpine
    container_name: weather-api-redis
    ports:
      - "6379:6379"
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge